# frozen_string_literal: true

require 'bundler/gem_tasks'
require 'rake/testtask'
require 'rb_sys/extensiontask'

GEMSPEC = Gem::Specification.load('litsea.gemspec')

RbSys::ExtensionTask.new('litsea-ruby', GEMSPEC) do |ext|
  ext.lib_dir = 'lib/litsea'
end

Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.libs << 'lib'
  t.test_files = FileList['test/**/test_*.rb']
  t.warning = false
end

task default: %i[compile test]
