/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A flag that asks a running training job to stop.
 *
 * Cancelling is cooperative and is **not** an error: training stops at its
 * next check point, still writes the partially trained model, and resolves
 * with its metrics. The binding never installs a signal handler.
 */
export declare class CancelToken {
  /**
   * Creates a token in the "keep running" state.
   *
   * # Returns
   * The new `CancelToken`.
   */
  constructor()
  /** Requests cancellation. */
  cancel(): void
  /** Returns the token to the "keep running" state. */
  reset(): void
  /** Whether cancellation has been requested. */
  get cancelled(): boolean
}
export type JsCancelToken = CancelToken

/** Extracts training features from a corpus. */
export declare class Extractor {
  /**
   * Creates an extractor for a language.
   *
   * # Arguments
   * * `language` - A language name or ISO 639-1 code.
   *
   * # Returns
   * The new `Extractor`.
   *
   * # Errors
   * Throws an error with the `invalid_argument` code for an unknown
   * language.
   */
  constructor(language: string)
  /**
   * Extracts boundary-classification features off the event loop.
   *
   * # Arguments
   * * `corpus_path` - Path to the training corpus.
   * * `features_path` - Path of the features file to write.
   * * `tsv` - Read the corpus in the space-preserving TSV format.
   * * `tag_free` - Omit tag-dependent feature templates.
   *
   * # Returns
   * A promise resolving once the features file has been written.
   */
  extract(corpusPath: string, featuresPath: string, tsv?: boolean | undefined | null, tagFree?: boolean | undefined | null): Promise<void>
  /**
   * Extracts two-stage (segmentation + POS) features off the event loop.
   *
   * Writes `{outputPrefix}.stage1`, `.stage2`, and `.lexicon`.
   *
   * # Arguments
   * * `corpus_path` - Path to the POS-tagged training corpus.
   * * `output_prefix` - Prefix for the three output files.
   * * `feature_set` - `"full"`, `"balanced"`, or `"fast"`; defaults to
   *   `"fast"`.
   * * `tsv` - Read the corpus in the space-preserving TSV format.
   *
   * # Returns
   * A promise resolving once all three files have been written.
   *
   * # Errors
   * Throws an error with the `invalid_argument` code for an unknown
   * feature set.
   */
  extractTwoStage(corpusPath: string, outputPrefix: string, featureSet?: string | undefined | null, tsv?: boolean | undefined | null): Promise<void>
}
export type JsExtractor = Extractor

/** Trains a label-agnostic Averaged Perceptron model. */
export declare class PerceptronTrainer {
  /**
   * Loads a features file and prepares training.
   *
   * # Arguments
   * * `num_epochs` - Number of passes over the training data.
   * * `features_path` - Path to the features file.
   *
   * # Returns
   * The new `PerceptronTrainer`.
   *
   * # Errors
   * Throws an error with the `io` or `parse` code if the features file
   * cannot be read.
   */
  constructor(numEpochs: number, featuresPath: string)
  /**
   * Trains the model off the event loop and writes it to `modelPath`.
   *
   * # Arguments
   * * `model_path` - Path of the model file to write.
   * * `cancel` - Optional `CancelToken`.
   *
   * # Returns
   * A promise resolving to the training metrics.
   */
  train(modelPath: string, cancel?: CancelToken | undefined | null): Promise<MulticlassMetrics>
}
export type JsPerceptronTrainer = PerceptronTrainer

/**
 * A word segmenter, optionally with POS tagging.
 *
 * Build one with `Segmenter.open`, `Segmenter.fromBytes`, or
 * `Segmenter.fromUri`. The kind of model is detected from the file itself,
 * so `hasPos` describes what was loaded rather than something the caller
 * has to declare.
 */
export declare class Segmenter {
  /**
   * Loads a model from a filesystem path.
   *
   * # Arguments
   * * `language` - A language name or ISO 639-1 code (`"japanese"`, `"ja"`).
   * * `path` - Path to the model file.
   *
   * # Returns
   * The new `Segmenter`.
   *
   * # Errors
   * Throws an error whose `code` is `invalid_argument`, `io`, `parse`, or
   * `model`.
   */
  static open(language: string, path: string): Segmenter
  /**
   * Loads a model from raw bytes.
   *
   * # Arguments
   * * `language` - A language name or ISO 639-1 code.
   * * `data` - The model file contents.
   *
   * # Returns
   * The new `Segmenter`.
   *
   * # Errors
   * Throws an error whose `code` is `invalid_argument`, `parse`, or
   * `model`.
   */
  static fromBytes(language: string, data: Buffer): Segmenter
  /**
   * Loads a model from a URI, resolving once it is available.
   *
   * Accepts a filesystem path, a `file://` path, or an `http(s)://` URL.
   * The download runs on a worker thread, so the event loop keeps
   * turning.
   *
   * # Arguments
   * * `language` - A language name or ISO 639-1 code.
   * * `uri` - The model URI.
   *
   * # Returns
   * A promise resolving to the new `Segmenter`.
   *
   * # Errors
   * Rejects with an error whose `code` is `invalid_argument`, `model`,
   * `io`, or `parse`.
   */
  static fromUri(language: string, uri: string): Promise<Segmenter>
  /** The language this segmenter was built for. */
  get language(): string
  /** Whether this segmenter can tag parts of speech. */
  get hasPos(): boolean
  /**
   * Splits a sentence into tokens.
   *
   * # Arguments
   * * `text` - The sentence to segment.
   *
   * # Returns
   * The tokens, in order.
   */
  segment(text: string): Array<string>
  /**
   * Splits several sentences into tokens, reusing one scratch buffer.
   *
   * # Arguments
   * * `texts` - The sentences to segment.
   *
   * # Returns
   * One token array per input sentence, in input order.
   */
  segmentBatch(texts: Array<string>): Array<Array<string>>
  /**
   * Splits a sentence into tokens carrying byte offsets.
   *
   * # Arguments
   * * `text` - The sentence to segment.
   *
   * # Returns
   * The tokens, with `pos` set to `null`.
   */
  segmentTokens(text: string): Array<Token>
  /**
   * Splits a sentence into tokens and tags each with a UPOS tag.
   *
   * # Arguments
   * * `text` - The sentence to segment and tag.
   *
   * # Returns
   * The tagged tokens, with byte offsets into `text`.
   *
   * # Errors
   * Throws an error with the `pos_unavailable` code when this segmenter
   * was built from a segmentation-only model.
   */
  segmentWithPos(text: string): Array<Token>
  /**
   * Splits and tags several sentences.
   *
   * # Arguments
   * * `texts` - The sentences to segment and tag.
   *
   * # Returns
   * One tagged-token array per input sentence, in input order.
   *
   * # Errors
   * Throws an error with the `pos_unavailable` code when this segmenter
   * was built from a segmentation-only model.
   */
  segmentWithPosBatch(texts: Array<string>): Array<Array<Token>>
}
export type JsSegmenter = Segmenter

/** Trains a segmentation model. */
export declare class Trainer {
  /**
   * Loads a features file and prepares training.
   *
   * # Arguments
   * * `threshold` - Early-stopping threshold for weak classifiers.
   * * `num_iterations` - Maximum number of boosting iterations.
   * * `features_path` - Path to the features file.
   *
   * # Returns
   * The new `Trainer`.
   *
   * # Errors
   * Throws an error with the `io` or `parse` code if the features file
   * cannot be read.
   */
  constructor(threshold: number, numIterations: number, featuresPath: string)
  /**
   * Trains the model off the event loop and writes it to `modelPath`.
   *
   * # Arguments
   * * `model_path` - Path of the model file to write.
   * * `cancel` - Optional `CancelToken`; cancelling stops training early
   *   and still writes the partially trained model.
   *
   * # Returns
   * A promise resolving to the training metrics.
   */
  train(modelPath: string, cancel?: CancelToken | undefined | null): Promise<BinaryMetrics>
}
export type JsTrainer = Trainer

/**
 * Trains a two-stage segmentation + POS model.
 *
 * A trainer can only be used once: training collapses stage 1 into an
 * AdaBoost model, which consumes it. `available` reports the state, and a
 * second `train()` rejects with an `invalid_argument` error.
 */
export declare class TwoStageTrainer {
  /**
   * Loads a two-stage features prefix and prepares training.
   *
   * # Arguments
   * * `num_epochs` - Number of passes over the training data.
   * * `features_prefix` - Prefix of the `.stage1` / `.stage2` /
   *   `.lexicon` files.
   * * `dominance` - Lexicon dominance threshold in `(0.5, 1.0]`;
   *   defaults to 0.99.
   *
   * # Returns
   * The new `TwoStageTrainer`.
   *
   * # Errors
   * Throws an error with the `invalid_argument` code if `dominance` is
   * out of range, or `io` / `parse` if the feature files cannot be read.
   */
  constructor(numEpochs: number, featuresPrefix: string, dominance?: number | undefined | null)
  /** Whether this trainer can still be used. */
  get available(): boolean
  /**
   * Trains both stages off the event loop and writes the model.
   *
   * # Arguments
   * * `model_path` - Path of the model file to write.
   * * `cancel` - Optional `CancelToken`.
   *
   * # Returns
   * A promise resolving to the metrics of both stages.
   *
   * # Errors
   * Rejects with an `invalid_argument` error if the trainer has already
   * been used.
   */
  train(modelPath: string, cancel?: CancelToken | undefined | null): Promise<TwoStageMetrics>
}
export type JsTwoStageTrainer = TwoStageTrainer

/**
 * Metrics from training a binary (segmentation) model.
 *
 * All percentages are 0-100.
 */
export interface JsBinaryMetrics {
  /** Accuracy, as a percentage. */
  accuracy: number
  /** Precision, as a percentage. */
  precision: number
  /** Recall, as a percentage. */
  recall: number
  /** Number of training instances. */
  numInstances: number
  /** True positives. */
  truePositives: number
  /** False positives. */
  falsePositives: number
  /** False negatives. */
  falseNegatives: number
  /** True negatives. */
  trueNegatives: number
}

/**
 * Metrics from training a multiclass model.
 *
 * All percentages are 0-100. The per-class counts are objects keyed by the
 * label name.
 */
export interface JsMulticlassMetrics {
  /** Accuracy, as a percentage. */
  accuracy: number
  /** Macro-averaged precision, as a percentage. */
  macroPrecision: number
  /** Macro-averaged recall, as a percentage. */
  macroRecall: number
  /** Number of training instances. */
  numInstances: number
  /** Correct predictions per class. */
  correctPerClass: Record<string, number>
  /** Predictions made per class. */
  predictedPerClass: Record<string, number>
  /** Gold instances per class. */
  goldPerClass: Record<string, number>
}

/** Metrics from training a two-stage model: one set per stage. */
export interface JsTwoStageMetrics {
  /** Boundary-classifier (stage 1) metrics. */
  stage1: JsMulticlassMetrics
  /** Word-level tagger (stage 2) metrics. */
  stage2: JsMulticlassMetrics
}

/**
 * Returns the names of every supported language.
 *
 * # Returns
 * The canonical names, in documentation order.
 */
export declare function supportedLanguages(): Array<string>

/**
 * A segmented token.
 *
 * `start` and `end` are byte offsets into the input string, so
 * `Buffer.from(text).subarray(token.start, token.end).toString()` returns
 * the surface. They are exact for both segmentation and POS output,
 * including for space-preserving languages, where the whitespace itself is
 * a token.
 *
 * Note that JavaScript string indices are UTF-16 code units, so these
 * offsets are not directly usable with `String.prototype.slice`.
 */
export interface Token {
  /** The token's surface form. */
  surface: string
  /**
   * The UPOS tag name (for example `"NOUN"`), or `undefined` when the
   * segmenter has no POS model (napi maps `None` to `undefined`).
   */
  pos?: string
  /** Starting byte offset in the input string. */
  start: number
  /** Ending byte offset (exclusive) in the input string. */
  end: number
}

/**
 * Returns the version of the underlying `litsea` crate.
 *
 * # Returns
 * The version string, for example `"0.12.0"`.
 */
export declare function version(): string
